### PR TITLE
presentational changes needed to close #31

### LINKED ISSUE #31: 'ADD COMMENT' button easy to miss
For the posts I answer, it is most common that users ignore the small blue-on-grey "ADD COMMENT" button or "ADD REPLY" button and instead use the large green "Add Answer" button.

So they end up adding Answer, when they are really want to respond to an Answer, and so the site doesn't really benefit from threading.

I'd suggest making these buttons (add comment / add reply) be larger and have brighter colors to compete visually with "Add Answer".

Note that the "Add Answer" button is used most often by regular visitors to the support site (developers) while the "Add Comment" / "Add Reply" buttons should be aimed at the new visitors, so we should make it easier for them to spot.

### PR DESCRIPTION
**Pull request by schifferl**

### CODE REVIEW

**Comment by schifferl** [comment]
I have also added the MathJax library, as this was something Wolfgang Huber had requested. A working example can be seen at <https://184.72.110.235/p/98365/>

**Comment by schifferl** [comment]
Sorry to keep adding things, but I wanted to fix the rest of the issues Aaron Lun brought up in his post at <https://184.72.110.235/p/98365/>. So, additional fixes now include line wrapping in markdown mode.

**Comment by lshep** [comment]
I am waiting to merge this until after the release -  the tentative date for merging and deployment is May 7 or 8.

**Comment by schifferl** [comment]
bitmoji

**Comment by lshep** [comment]
It seems there is an issue with firefox tho?   Was this because of my change or do you have any input?

**Pull request merged**
